### ISSUE TITLE
HardhatError: HH700: Artifact for contract "SimpleStorage" not found.

### ISSUE THREAD

**Issue by EnricoYu** [PatrickAlphaC/hardhat-simple-storage-fcc#14]
I have this error at the start of Hardhat section

This is deploy.js:
const { ethers } = require("hardhat");

async function main() {
  const SimpleStorageFactory = await ethers.getContractFactory("SimpleStorage");
  console.log("Deploying contract...");
  const simpleStorage = await SimpleStorageFactory.deploy();
  await simpleStorage.deployed();
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

after I type: yarn hardhat run scripts/deploy.js
HardhatError: HH700: Artifact for contract "SimpleStorage" not found. 
    at Artifacts._handleWrongArtifactForContractName (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/artifacts.ts:478:11)
    at Artifacts._getArtifactPathFromFiles (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/artifacts.ts:593:19)
    at Artifacts._getArtifactPath (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/artifacts.ts:275:17)
    at Artifacts.readArtifact (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/artifacts.ts:58:26)
    at getContractFactory (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:99:22)
    at main (/Users/enricoyu/Coding/hardhat-simple-storage-fcc/scripts/deploy.js:4:32)
error Command failed with exit code 1.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
