### ISSUE TITLE
Coverage plugin broken

### ISSUE THREAD

**Issue by psabadac** [PatrickAlphaC/hardhat-simple-storage-fcc#28]
I installed the coverage plugin, I even did a hardhat clean but I am still receiving this error:

I googled a bit, but I was unable to find a working solution (even tried installed the 0.8.0-beta.1 coverage plugin did not help.

Please advise.
Thank you!

```sv@DESKTOP-JCDEGO3:~/hh-fcc/hardhat-simple-storage-fcc$ yarn hardhat coverage --show-stack-traces
yarn run v1.22.15
$ /home/sv/hh-fcc/hardhat-simple-storage-fcc/node_modules/.bin/hardhat coverage --show-stack-traces

Version
=======
> solidity-coverage: v0.8.0-beta.1

Instrumenting for coverage...
=============================

> SimpleStorage.sol

Compilation:
============

Nothing to compile
Error in plugin solidity-coverage: TypeError: cur._node._vm.on is not a function

HardhatPluginError: TypeError: cur._node._vm.on is not a function
    at SimpleTaskDefinition.action (/home/sv/hh-fcc/hardhat-simple-storage-fcc/node_modules/solidity-coverage/plugins/hardhat.plugin.js:245:35)
    at Environment._runTaskDefinition (/home/sv/hh-fcc/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/home/sv/hh-fcc/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at main (/home/sv/hh-fcc/hardhat-simple-storage-fcc/node_modules/hardhat/src/internal/cli/cli.ts:269:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by RyanPaulGannon** [comment]
I also had a `TypeError`, but it was due to what I'd missed in my `test-deploy.ts`. I hadn't imported `import { SimpleStorage, SimpleStorage__factory } from "../typechain-types"`. What does your `config` and `test` files look like?

**Comment by psabadac** [comment]
Thanks for the replay! Nah, I am using `test-depoloy.js`. So not .ts. Never mind, I cloned again the repo, did yarn (to initialize all the packages) and now everything works.
