### ISSUE TITLE
Error when running deploy.js with function "deployTransaction"

### ISSUE THREAD

**Issue by nicolasraus** [PatrickAlphaC/hardhat-simple-storage-fcc#53]
Hi all!
I've been following the steps from the video and with this code:
```// imports
const { ethers, run, network } = require("hardhat")

// async main
async function main() {
  const SimpleStorageFactory = await ethers.getContractFactory("SimpleStorage")
  console.log("Deploying contract...")
  const simpleStorage = await SimpleStorageFactory.deploy()
  await simpleStorage.deployed()
  console.log(`Deployed contract to: ${simpleStorage.address}`)
  }

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })
```
I get the following error:
```yarn hardhat run scripts/deploy.js --network sepolia
yarn run v1.22.19
$ /home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/.bin/hardhat run scripts/deploy.js --network sepolia
Deploying contract :)
TypeError: no matching function (argument="key", value="deployed", code=INVALID_ARGUMENT, version=6.6.1)
    at makeError (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:670:21)
    at assert (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:694:25)
    at assertArgument (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:706:5)
    at Interface.getFunctionName (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/abi/interface.ts:542:23)
    at buildWrappedMethod (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:334:34)
    at BaseContract.getFunction (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:849:22)
    at Object.get (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:747:39)
    at main (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/scripts/deploy.js:7:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'deployed'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After googling I discovered that there is a new version of hardhat (or ethers?) so those functions had been changed, so I updated my code to this:
```const { ethers, run, network } = require("hardhat")

async function main() {
    console.log("Deploying contract :)")
    const simpleStorage = await ethers.deployContract("SimpleStorage")
    await simpleStorage.waitForDeployment()
    console.log(`Deployed contract to: ${await simpleStorage.getAddress()}`)
    if (network.config.chainId === 11155111 && process.env.ETHERSCAN_API_KEY) {
        await simpleStorage.deployTransaction.wait(6)
        await verify(await simpleStorage.getAddress(), [])
    }
}

async function verify(contractAddress, args) {
    console.log("Verifying contract :)")
    try {
        await run("verify:verify", {
            address: contractAddress,
            constructorArgsParams: args,
        })
    } catch (e) {
        if (e.message.toLowerCase().includes("already verified")) {
            console.log("Already verified!")
        } else {
            console.log(e)
        }
    }
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })
```
But then I get the following error:
```
yarn hardhat run scripts/deploy.js --network sepolia
yarn run v1.22.19
$ /home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/.bin/hardhat run scripts/deploy.js --network sepolia
Deploying contract :)
Deployed contract to: 0x3d3Cf67b7E2110f934a56A8020252421079b1120
TypeError: no matching function (argument="key", value="deployTransaction", code=INVALID_ARGUMENT, version=6.6.1)
    at makeError (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:670:21)
    at assert (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:694:25)
    at assertArgument (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/utils/errors.ts:706:5)
    at Interface.getFunctionName (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/abi/interface.ts:542:23)
    at buildWrappedMethod (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:334:34)
    at BaseContract.getFunction (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:849:22)
    at Object.get (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/node_modules/ethers/src.ts/contract/contract.ts:747:39)
    at main (/home/user/Documents/learning/blockchain/smart-contracts-learning/hardhat-simple-storage/scripts/deploy.js:9:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'deployTransaction'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So my question would be, is there a new version of deployTransaction that I should be using? Or which version of hardhat/ethers should I specify with yarn so I can use the code from the course?
Thanks :)

**Comment by nicolasraus** [comment]
Well, I solved it by doing:
```
 $  yarn add --dev hardhat@2.14.0
 $  yarn add --dev @nomicfoundation/hardhat-toolbox@2.0.2
 $  yarn add --dev "@nomiclabs/hardhat-ethers@^2.0.0" "@nomiclabs/hardhat-etherscan@^3.0.0" "@types/mocha@>=9.1.0" "@typechain/ethers-v5@^10.1.0" "ethers@^5.4.7" "ts-node@>=8.0.0" "typescript@>=4.5.0"
```
I don't know if this is ok, but it worked!
