### ISSUE TITLE
issue with deployment using hardhat 

### ISSUE THREAD

**Issue by Alok-Raturi** [PatrickAlphaC/hardhat-simple-storage-fcc#55]
TypeError: no matching function (argument="key", value="address", code=INVALID_ARGUMENT, version=6.6.2)
    at makeError (/root/hardhat-core/node_modules/ethers/src.ts/utils/errors.ts:670:21)
    at assert (/root/hardhat-core/node_modules/ethers/src.ts/utils/errors.ts:694:25)
    at assertArgument (/root/hardhat-core/node_modules/ethers/src.ts/utils/errors.ts:706:5)
    at Interface.getFunctionName (/root/hardhat-core/node_modules/ethers/src.ts/abi/interface.ts:542:23)
    at buildWrappedMethod (/root/hardhat-core/node_modules/ethers/src.ts/contract/contract.ts:334:34)
    at BaseContract.getFunction (/root/hardhat-core/node_modules/ethers/src.ts/contract/contract.ts:849:22)
    at Object.get (/root/hardhat-core/node_modules/ethers/src.ts/contract/contract.ts:747:39)
    at main (/root/hardhat-core/scripts/deploy.js:7:54)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'address'
}

My code is giving this error and here is the code 
```
const { ethers } = require("hardhat");

async function main() {
  const SimpleStorageFactory = await ethers.getContractFactory("SimpleStorage");
  console.log("deploying contract");
  const simpleStorage = await SimpleStorageFactory.deploy();
  await simpleStorage.deployed();
  console.log(`Deployed contract to: ${simpleStorage.address}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.log(error);
    process.exit(1);
  });

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by hamzarana07** [comment]
Having the same issue. Need help please. Nothing works. Tried various methods.
Hardhat cannot find this: 
`await simpleStorage.deployed()`
I also tried:
`await simpleStorage.deployTransaction.wait();`

**Comment by Taruns123** [comment]
I also got the error and this solution worked for me
instead of simpleStorage.deployed() use:
```nodejs
await simpleStorage.waitForDeployment(1);
```

and there is no such call for address on simpleStorage contract so use this instead of simpleStorage.address
```nodejs
  console.log(await simpleStorage.getAddress());
```
