### ISSUE TITLE
Deployment issues with HardHat

### ISSUE THREAD

**Issue by hamzarana07** [PatrickAlphaC/hardhat-simple-storage-fcc#56]
On YouTube, I am on the **08:41:03** mark.

```
const { ethers, run, network } = require("hardhat")

async function main() {
    const SimpleStorageFactory = await ethers.getContractFactory(
        "SimpleStorage"
    )
    console.log("Deploying contract...")
    const simpleStorage = await SimpleStorageFactory.deploy()
    await simpleStorage.deployed()
    console.log(simpleStorage)
}
```

This returns the following error:
```
TypeError: no matching function (argument="key", value="deployed", code=INVALID_ARGUMENT, version=6.6.3)
    at makeError (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/utils/errors.ts:670:21)
    at assert (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/utils/errors.ts:694:25)
    at assertArgument (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/utils/errors.ts:706:5)
    at Interface.getFunctionName (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/abi/interface.ts:542:23)
    at buildWrappedMethod (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/contract/contract.ts:334:34)
    at BaseContract.getFunction (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/contract/contract.ts:859:22)
    at Object.get (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/node_modules/ethers/src.ts/contract/contract.ts:757:39)
    at main (/home/hamza/Documents/JS/Ethersjsx/hardhat/SimpleStorage/scripts/deploy.js:10:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'deployed'
}
```

Yarn Version:
`1.22.19`

HardHat Version:
`2.17.0`

Node Version:
`20.3.1`

**Comment by Nicolaswg** [comment]
Hi @hamzarana07, this error might be something that is not supported y the newer version of Hardhat as they would be like `contract.deployed() --- contract.deployTransaction.wait()`.

These functions have the same error, you could try to use this syntax instead: 
``` const SimpleStorageFactory = await ethers.getContractFactory("SimpleStorage");
  console.log("Deploying Contract...");
  const simpleStorage = await SimpleStorageFactory.deploy();
  await simpleStorage.waitForDeployment();
  console.log("Contract deployed to:", simpleStorage.target)```
  
Give a look at the contract attribute as well because some keys are not the same, an example of that would be `simpleStorage.address` and change it to `simpleStorage.target`

**Comment by hamzarana07** [comment]
Thank you so much this worked. Even though I tried various solutions from other places, but this did it. Thanks again.
