### ISSUE TITLE
Error: could not decode result data (value="0x", info={ "method": "retrieve", "signature": "retrieve()" }, code=BAD_DATA, version=6.7.1)

### ISSUE THREAD

**Issue by Jamsce** [PatrickAlphaC/hardhat-simple-storage-fcc#57]
When I run the following command, there is an error, and the address given cannot query the transaction information, but the ether of the testnet has decreased, how to solve the following error?

npx hardhat run scripts/deploy.js --network sepolia
Deploying contract...
Deployed contract to: 0x07Dd85d9E00e9C8dB0200ace73ec66C11f4e2f44
Error: could not decode result data (value="0x", info={ "method": "retrieve", "signature": "retrieve()" }, code=BAD_DATA, version=6.7.1)    
    at makeError (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\utils\errors.ts:685:21)
    at assert (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\utils\errors.ts:702:25)
    at Interface.decodeFunctionResult (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\abi\interface.ts:916:15)
    at staticCallResult (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\contract\contract.ts:332:35)        
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at staticCall (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\contract\contract.ts:289:24)
    at Proxy.retrieve (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\node_modules\ethers\src.ts\contract\contract.ts:337:41)
    at main (C:\Users\Jamscs\solidity\hardhat-simple-storage-fcc\scripts\deploy.js:16:24) {
  code: 'BAD_DATA',
  value: '0x',
  info: { method: 'retrieve', signature: 'retrieve()' }
}

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
