### ISSUE TITLE
JsonRpcProvider is not found

### ISSUE THREAD

**Issue by SanthiyaMeganathan** [PatrickAlphaC/hardhat-simple-storage-fcc#69]
the error i got
```
node deploy.js
TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')
    at main (/home/santhiya_1321/hh-fcc/ethers-simple-storage-fcc/deploy.js:6:41)
    at Object.<anonymous> (/home/santhiya_1321/hh-fcc/ethers-simple-storage-fcc/deploy.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

```solidity
const { ethers } = require("ethers");
const fs = require("fs-extra");

// async main
async function main() {
  const provider = new ethers.providers.JsonRpcProvider(
    "HTTP://127.0.0.1:7545"
  );

  const wallet = new ethers.Wallet(
    "0x284ede9545b2639b2ec29a5bc7a78cade4d320470a7a99eb560a700017dc591b",
    provider
  );
  const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf-8");
  const binary = fs.readFileSync(
    "./SimpleStorage_sol_SimpleStorage.bin",
    "utf-8"
  );

  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("Please wait we are deploying our contract");
  //code to deploy our contract
  const contract = await contractFactory.deploy();
}

// main
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by PatrickAlphaC** [comment]
Sorry you got this. We are in the process of archiving this repo, and won't be maintaining it moving forward.

Can you:
1. Make this a discussion on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
